spring:
  application:
    name: intelli_code_ldi_agent

  datasource:
    url: jdbc:postgresql://localhost:5433/intellic_db
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        default-schema: public
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl: update
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY:}
        chat:
          options:
            model: gemini-3.5-flash
            temperature: 1.0
        embedding:
          api-key: ${GOOGLE_API_KEY:}
          text:
            options:
              model: gemini-embedding-001

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        dimension: 1536
        distance-type: COSINE_DISTANCE
        table-name: vector_store
        schema-name: public

logging:
  level:
    org.springframework.ai.openai: DEBUG